export const cuisineList = [
  "Tunisienne",
  "Grillades",
  "Petit-déjeuner",
  "Sandwichs",
  "Café",
  "Asiatique",
  "Pâtisseries",
  "Française",
  "Méditerranéenne",
  "Healthy",
  "Orientale",
  "Italienne",
  "Japonaise",
  "Mexicaine",
  "Pâtes",
  "Bio",
  "Briks",
  "Pizza",
  "Salades",
  "Poissons & Fruits de mer",
  "Espagnole",
  "Viandes",
  "Sushi",
  "Tacos",
  "Tapas",
  "Végétarien"
];
